[package]
name = "drv-errors-derive"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "^2.0.110", features = ["full", "extra-traits"] }
quote = "^1.0.42"

[lints]
workspace = true
